name: build
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]
        env:
            USING_COVERAGE: "3.10"
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: make deps
            - name: Check pep8
              run: |
                  python3 -m pflake8 pure_utils/
                  python3 -m pflake8 --ignore=F401 tests/
            - name: Check code style
              run: |
                  python3 -m black --line-length 100 --check pure_utils/
                  python3 -m black --line-length 100 --check tests/
            - name: Check imports
              run: |
                  python3 -m isort -c -v pure_utils/
                  python3 -m isort -c -v tests/
            - name: Check types
              run: |
                  python3 -m mypy --install-types --non-interactive pure_utils/
            - name: Check docstrings
              run: |
                  python3 -m pydocstyle
            - name: Run tests
              run: |
                  pytest --cov pure_utils/ --cov-report term
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
